# Change these first
owner: intentop # Your GitHub username
repo: salon-uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Salon Love
    url: https://www.salon-love-forever.ru/wedding/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#  cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /salon-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Salon
  introTitle: "Статус сайта salon-love-forever.ru"
  introMessage: Проверка жизни сайта
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
